# github action workflow for deploying the portfolio site to GitHub Pages
name: Deploy to GitHub Pages

#  triggers the workflow when a push is made to the main branch
on:
  push:
    branches: [main]

# permissions needed for this workflow:
#    - 'contents:read' allows actions to read repository contents
#    - 'pages:write' allows actions to write to GitHub Pages
#    - 'id-token:write' allows generating OpenID Connect (OIDC) tokens, needed by some GitHub Actions for authentication
permissions:
  contents: read
  pages: write
  id-token: write

# jobs needed for this workflow:
jobs:
  # build will run on the latest ubuntu runner and build the portfolio site
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v4

      # setup node.js v20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # install dependencies using npm ci (clean install, reccomended for CI environments)
      - name: Install dependencies
        run: npm ci

      # run the build script defined in package.json (e.g., npm run build)
      - name: Build
        run: npm run build

      # upload the output of the build process as an artifact named 'pages-artifact' for passing build output to next job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # build job finished, now deploy to GitHub Pages
  deploy:
    # deploying on ubuntu-latest runner
    # steps.deployment.outputs.page_url is the URL of the GitHub Pages site generated by the build job
    # expected output: https://<username>.github.io/<repository>
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # build job must finish successfully before deploying
    needs: build
    steps:
      # deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
